import { createAssetsClient, validateCollection } from './sdk.mjs';
import { zipSync, strToU8 } from './vendor/fflate.mjs';
const client=createAssetsClient({baseUrl:location.origin});const initial=JSON.parse(document.querySelector('#library-data')?.textContent||'{}');
const $=selector=>document.querySelector(selector);const e=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const storageKey='shirtlab.wiki.collections.v1';let saved,storageAvailable=true;
try{saved=JSON.parse(localStorage.getItem(storageKey)||'null');if(!saved||!Array.isArray(saved.collections)||saved.collections.length>100)throw Error();saved.collections=saved.collections.map(c=>({...validateCollection(c),key:typeof c.key==='string'?c.key:crypto.randomUUID()}));if(!saved.collections.some(c=>c.key===saved.active))saved.active=saved.collections[0]?.key;}catch{saved={collections:[],active:null};}
if(!saved.collections.length){const key=crypto.randomUUID();saved={collections:[{schema:'shirtlab.collection.v1',key,name:'My collection',assets:[]}],active:key};}
const current=()=>saved.collections.find(c=>c.key===saved.active);let zipCursor=0;
function persist(){try{localStorage.setItem(storageKey,JSON.stringify(saved));}catch{storageAvailable=false;$('#collection-status').textContent='Device storage is unavailable. Export JSON to keep your collection.';}updateButtons();}
function updateButtons(){const ids=new Set(current().assets);$('#collection-count').textContent=String(ids.size);for(const b of document.querySelectorAll('[data-collect]')){const collected=ids.has(b.dataset.collect);b.textContent=collected?'Collected ✓':'Collect';b.setAttribute('aria-pressed',String(collected));b.setAttribute('aria-label',(collected?'Remove ':'Add ')+b.dataset.collect+(collected?' from collection':' to collection'));}}
function collectionItems(){const c=current();$('#collection-picker').innerHTML=saved.collections.map(item=>`<option value="${e(item.key)}"${item.key===saved.active?' selected':''}>${e(item.name)} (${item.assets.length})</option>`).join('');$('#collection-items').innerHTML=c.assets.map(id=>{const[pack,name]=id.split(':');return`<li><a href="/wiki/${e(pack)}/${e(name)}/">${e(id)}</a><button type="button" data-remove="${e(id)}" aria-label="Remove ${e(id)}">Remove</button></li>`;}).join('')||'<li>Your collection is empty. Choose Collect on any asset.</li>';$('#zip-collection').disabled=!c.assets.length;$('#export-collection').disabled=!c.assets.length;$('#zip-collection').textContent=zipCursor?'Download next ZIP batch':'Download ZIP';}
function openCollection(){collectionItems();$('#collection-dialog').showModal();}
$('#open-collection').addEventListener('click',openCollection);$('#close-collection').addEventListener('click',()=>$('#collection-dialog').close());
$('#collection-picker').addEventListener('change',event=>{saved.active=event.target.value;zipCursor=0;persist();collectionItems();});
$('#new-collection').addEventListener('submit',event=>{event.preventDefault();const name=$('#collection-name').value.trim();if(!name)return;if(saved.collections.length>=100){$('#collection-status').textContent='Export an existing collection before creating another. This device supports 100 collections.';return;}const key=crypto.randomUUID();saved.collections.push({schema:'shirtlab.collection.v1',key,name,assets:[]});saved.active=key;zipCursor=0;$('#collection-name').value='';persist();collectionItems();});
document.addEventListener('click',event=>{const button=event.target.closest('button[data-collect],button[data-remove]');if(!button)return;const id=button.dataset.collect||button.dataset.remove,c=current();if(c.assets.includes(id))c.assets=c.assets.filter(item=>item!==id);else{if(c.assets.length>=2000){openCollection();$('#collection-status').textContent='This collection has 2,000 assets. Create another collection to keep adding.';return;}c.assets.push(id);}zipCursor=0;persist();if($('#collection-dialog').open)collectionItems();});
function saveFile(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
const safeName=name=>name.replace(/[^a-zA-Z0-9_-]+/g,'-').slice(0,70)||'shirtlab-collection';
$('#export-collection').addEventListener('click',()=>{const c=current();saveFile(new Blob([JSON.stringify({schema:c.schema,name:c.name,assets:c.assets,version:initial.version},null,2)],{type:'application/json'}),safeName(c.name)+'.shirtlab-collection.json');});
$('#import-collection').addEventListener('change',async event=>{try{const file=event.target.files[0];if(!file)return;if(file.size>1_000_000)throw Error('Choose a collection JSON file smaller than 1 MB.');if(saved.collections.length>=100)throw Error('This device already has 100 collections.');const c=validateCollection(JSON.parse(await file.text()));c.key=crypto.randomUUID();saved.collections.push(c);saved.active=c.key;zipCursor=0;persist();collectionItems();$('#collection-status').textContent='Collection imported. Asset IDs will be checked when downloaded.';}catch(error){$('#collection-status').textContent=error.message;}finally{event.target.value='';}});
$('#zip-collection').addEventListener('click',async()=>{
 const button=$('#zip-collection'),status=$('#collection-status'),c=current(),start=zipCursor;button.disabled=true;$('#collection-picker').disabled=true;let bytes=0;const files=Object.create(null),assets=[],licenses=new Set();
 try{for(let i=start;i<c.assets.length&&i<start+25;i++){
  status.textContent=`Preparing asset ${i+1} of ${c.assets.length}…`;const asset=await client.asset(c.assets[i]);const blob=await client.download(asset.id);if(blob.size>3_000_000)throw Error('An asset exceeds the download size limit. Download it from its wiki page.');if(bytes+blob.size>24*1024*1024&&assets.length)break;
  const name=asset.id.replace(':','--')+'.'+asset.format;files['assets/'+name]=new Uint8Array(await blob.arrayBuffer());bytes+=blob.size;assets.push(asset);
  if(!licenses.has(asset.pack.prefix)){const response=await fetch(new URL(asset.licenseUrl).pathname);if(!response.ok)throw Error('The licence notice could not be downloaded.');const notice=await response.text();if(notice.length>1_000_000)throw Error('The licence notice exceeds the download limit.');files['licenses/'+asset.pack.prefix+'.txt']=strToU8(notice);licenses.add(asset.pack.prefix);}
 }
 if(!assets.length)throw Error('This collection is empty.');
 files['collection.json']=strToU8(JSON.stringify({schema:'shirtlab.collection.v1',name:c.name,assets:assets.map(a=>a.id),version:assets[0].version},null,2));files['asset-metadata.json']=strToU8(JSON.stringify(assets,null,2));
 files['README.txt']=strToU8('Shirt Lab asset collection: '+c.name+'\n\nArtwork keeps its original creator and licence. Read licenses/ and asset-metadata.json, including individual declarations and brand guidelines.\n\n'+assets.map(a=>a.id+'\nCreator: '+a.pack.author.name+'\nLicence: '+a.license.spdx+'\nWiki: '+a.url+'\nAdd to a shirt: '+a.shirtUrl).join('\n\n'));
 status.textContent='Building ZIP…';await new Promise(resolve=>requestAnimationFrame(resolve));const zip=zipSync(files,{level:0});saveFile(new Blob([zip],{type:'application/zip'}),safeName(c.name)+'-'+(start+1)+'-'+(start+assets.length)+'.zip');zipCursor=start+assets.length;
 status.textContent=`Downloaded ${assets.length} assets with licences and shirt links.`+(zipCursor<c.assets.length?` ${c.assets.length-zipCursor} remain. Choose Download next ZIP batch.`:' Your complete collection is downloaded.');if(zipCursor>=c.assets.length)zipCursor=0;
 }catch(error){status.textContent=error.message;}finally{button.disabled=false;$('#collection-picker').disabled=false;collectionItems();}
});
let result=initial.result,controller,requestSerial=0;const searchForm=$('#asset-search');
function drawCard(asset){return`<li class="asset-card"><a class="preview" href="${e(asset.url)}"><img data-preview="${e(new URL(asset.previewUrl).pathname)}" alt="${e(asset.label)}" width="160" height="160" loading="lazy" decoding="async"></a><div class="card-text"><a class="asset-title" href="${e(asset.url)}">${e(asset.label)}</a><p>${e(asset.pack.name)} <span class="tag">${e(asset.format.toUpperCase())}</span></p><small>${e(asset.license.spdx)} · ${e(asset.pack.author.name)}</small><div class="card-actions"><button type="button" data-collect="${e(asset.id)}">Collect</button><a href="${e(asset.downloadUrl)}" download>Download</a><a href="${e(asset.shirtUrl)}">Add to a shirt</a></div></div></li>`;}
let previewQueue=[],previewJobs=0;const activePreviews=new Set(),urls=[];
const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){observer.unobserve(entry.target);previewQueue.push(entry.target);}pumpPreviews();},{rootMargin:'200px'});
function pumpPreviews(){while(previewJobs<4&&previewQueue.length){const image=previewQueue.shift();if(!image.isConnected)continue;previewJobs++;const abort=new AbortController();activePreviews.add(abort);fetch(image.dataset.preview,{signal:abort.signal}).then(r=>{if(!r.ok)throw Error();return r.blob();}).then(blob=>{if(!image.isConnected)return;const url=URL.createObjectURL(blob);urls.push(url);image.src=url;}).catch(()=>{image.alt+=' — preview unavailable';}).finally(()=>{previewJobs--;activePreviews.delete(abort);pumpPreviews();});}}
function resetPreviews(){observer.disconnect();previewQueue=[];for(const a of activePreviews)a.abort();for(const url of urls.splice(0))URL.revokeObjectURL(url);}
function params(){const p=new URLSearchParams(new FormData(searchForm));p.set('limit','48');return Object.fromEntries(p);}
async function search(offset=0,push=true){const serial=++requestSerial;controller?.abort();controller=new AbortController();const status=$('#search-status'),results=$('#results');results.setAttribute('aria-busy','true');status.textContent='Searching assets…';
 try{const next=await client.search({...params(),offset},{signal:controller.signal});if(serial!==requestSerial)return;result=next;resetPreviews();results.innerHTML=next.results.map(drawCard).join('')||'<li>No assets found. Try fewer words or another pack.</li>';for(const image of results.querySelectorAll('[data-preview]'))observer.observe(image);status.textContent=next.total.toLocaleString()+' assets'+(next.query?' matching “'+next.query+'”':'');$('#previous-page').disabled=offset===0;$('#next-page').disabled=next.nextOffset===null;$('#page-number').textContent=`Page ${Math.floor(offset/48)+1} of ${Math.max(1,Math.ceil(next.total/48))}`;updateButtons();results.scrollIntoView({block:'start',behavior:'instant'});if(push){const query=new URLSearchParams(params());query.delete('limit');for(const[key,value]of [...query])if(!value)query.delete(key);if(offset)query.set('offset',String(offset));history.pushState(null,'','/wiki/'+(query.size?'?'+query:''));} }catch(error){if(error.name!=='AbortError'&&serial===requestSerial)status.textContent='Search could not finish. Try again.';}finally{if(serial===requestSerial)results.setAttribute('aria-busy','false');}
}
if(searchForm){const query=new URLSearchParams(location.search);for(const key of ['q','pack','format','license'])if(query.has(key)&&searchForm.elements.namedItem(key))searchForm.elements.namedItem(key).value=query.get(key);searchForm.addEventListener('submit',event=>{event.preventDefault();search(0);});for(const select of searchForm.querySelectorAll('select'))select.addEventListener('change',()=>search(0));$('#previous-page').addEventListener('click',()=>search(Math.max(0,result.offset-48)));$('#next-page').addEventListener('click',()=>search(result.nextOffset||0));window.addEventListener('popstate',()=>{const p=new URLSearchParams(location.search);for(const key of ['q','pack','format','license'])searchForm.elements.namedItem(key).value=p.get(key)||'';search(Number(p.get('offset'))||0,false);});if(query.get('offset'))search(Number(query.get('offset')),false);}
document.addEventListener('keydown',event=>{if(searchForm&&((event.key.toLowerCase()==='k'&&(event.ctrlKey||event.metaKey))||(event.key==='/'&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName)))){event.preventDefault();$('#query').focus();}});
$('#pack-search')?.addEventListener('input',event=>{const query=event.target.value.toLowerCase();for(const li of document.querySelectorAll('[data-pack-label]'))li.hidden=!li.dataset.packLabel.includes(query);});
updateButtons();if(!storageAvailable)$('#collection-status').textContent='Export JSON to keep your collection.';